import { spawn, type ChildProcess, type SpawnOptions } from "child_process";
import os from "os";
import { z } from "zod";
import { MODEL } from "./config";
import type { ClaudeProvider, StructuredRequest } from "./provider";

const CLI_BINARY = "claude";

// generous: a full resume rewrite is a single long turn, and the CLI adds its own startup on top
// of the model call. Still bounded so a wedged child can never hang an API route forever.
const CLI_TIMEOUT_MS = 300000;

// how much of a failing CLI's output to quote back in an error message -- enough to diagnose,
// not so much that a route's JSON error becomes a wall of text
const ERROR_DETAIL_MAX_CHARS = 800;

/** Anything that went wrong reaching or running the CLI (as opposed to the model answering badly). */
export class ClaudeCliError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "ClaudeCliError";
  }
}

// only the two fields this provider actually reads, plus the failure flags. The CLI's JSON
// envelope is not a stable contract, so anything beyond these is deliberately ignored and a
// missing payload is reported loudly rather than silently treated as an empty answer.
interface CliEnvelope {
  is_error?: boolean;
  subtype?: string;
  result?: unknown;
  structured_output?: unknown;
}

export type SpawnFn = (command: string, args: string[], options: SpawnOptions) => ChildProcess;

export interface CliProviderOptions {
  spawnFn?: SpawnFn; // stubbed in tests; the real CLI is never invoked by the suite
  model?: string;
  timeoutMs?: number;
}

/**
 * Builds the CLI-backed provider: spawns `claude` in print mode with a JSON schema and reads the
 * structured answer back off stdout. This is the subscription-billed path -- the CLI uses the
 * user's Claude Code login, so no API credits are consumed.
 */
export function createCliProvider(opts: CliProviderOptions = {}): ClaudeProvider {
  const spawnFn = opts.spawnFn ?? (spawn as SpawnFn);
  const model = opts.model ?? MODEL;
  const timeoutMs = opts.timeoutMs ?? CLI_TIMEOUT_MS;

  const provider: ClaudeProvider = async <S extends z.ZodType>(req: StructuredRequest<S>) => {
    const args = buildCliArgs(req.system, req.schema, model);
    const stdout = await runCli(spawnFn, args, req.user, timeoutMs);
    const payload = extractPayload(stdout);

    // the CLI validated the payload against the same schema already; a mismatch here means the
    // envelope drifted, so treat it like the API path's null parsed_output and let the caller retry
    const parsed = req.schema.safeParse(payload);
    return parsed.success ? (parsed.data as z.infer<S>) : null;
  };

  return provider;
}

// pure so the exact flag set is pinned by a test rather than only by a live run
export function buildCliArgs(system: string, schema: z.ZodType, model: string): string[] {
  const jsonSchema = z.toJSONSchema(schema) as Record<string, unknown>;
  // the CLI's schema validator rejects the draft-2020-12 `$schema` ref zod emits ("no schema with
  // key or ref ..."), and the ref adds nothing here -- drop it
  delete jsonSchema.$schema;

  return [
    "-p",
    "--output-format",
    "json",
    "--model",
    model,
    "--json-schema",
    JSON.stringify(jsonSchema),
    "--append-system-prompt",
    system,
    // this is a pure text transformation: the agent must not read/write files or hit the network
    "--tools",
    "",
    // ignore this repo's CLAUDE.md/AGENTS.md, hooks, MCP servers and plugins. AGENTS.md is
    // regenerated by `next dev` and points agents at node_modules docs; none of it belongs in a
    // resume rewrite, and skipping it also cuts startup cost. Auth and model selection are unaffected.
    "--safe-mode",
    // benchmarked: default effort spends most of its ~150s wall time on thinking tokens before the
    // structured output lands (16k+ output tokens for a ~10k-char document). --effort low cuts wall
    // time ~2.3x and output tokens ~45% with identical validator/ATS results across repeated runs --
    // this is a rewrite-existing-content task, not one that benefits from deep reasoning.
    "--effort",
    "low",
  ];
}

/** Builds the child's env: identical to ours minus anything that would re-route the billing. */
export function cliEnv(parentEnv: NodeJS.ProcessEnv): NodeJS.ProcessEnv {
  const env = { ...parentEnv };
  // .env.local sets ANTHROPIC_API_KEY for the API provider, and Next puts it in process.env. If
  // the child inherited it the CLI would bill the metered API account -- the exact account with
  // no credits that this provider exists to avoid.
  delete env.ANTHROPIC_API_KEY;
  return env;
}

function runCli(
  spawnFn: SpawnFn,
  args: string[],
  input: string,
  timeoutMs: number
): Promise<string> {
  return new Promise((resolve, reject) => {
    let child: ChildProcess;
    try {
      child = spawnFn(CLI_BINARY, args, {
        // never through a shell: an interactive `claude` shell function injects --ide, and a shell
        // would turn the (untrusted, job-description-derived) prompt into an injection surface
        shell: false,
        // the CLI has no business in this repo -- keep it away from the resume and the tracker db
        cwd: os.tmpdir(),
        env: cliEnv(process.env),
        stdio: ["pipe", "pipe", "pipe"],
      });
    } catch (err) {
      reject(spawnFailure(err));
      return;
    }

    let stdout = "";
    let stderr = "";
    let settled = false;
    let timedOut = false;

    const finish = (fn: () => void) => {
      if (settled) return;
      settled = true;
      clearTimeout(timer);
      fn();
    };

    const timer = setTimeout(() => {
      timedOut = true;
      child.kill("SIGKILL");
      finish(() =>
        reject(
          new ClaudeCliError(
            `Claude Code CLI timed out after ${Math.round(timeoutMs / 1000)}s${detailSuffix(stderr)}`
          )
        )
      );
    }, timeoutMs);

    child.stdout?.on("data", (chunk) => (stdout += chunk));
    child.stderr?.on("data", (chunk) => (stderr += chunk));

    child.on("error", (err) => finish(() => reject(spawnFailure(err))));

    child.on("close", (code) => {
      if (timedOut) return; // the timeout already rejected; the close is just the kill landing
      finish(() => {
        if (code === 0) resolve(stdout);
        else reject(new ClaudeCliError(describeExitFailure(code, stderr, stdout)));
      });
    });

    // the prompt (resume + job description + whitelist) goes on stdin, not argv: it is far too
    // long for a comfortable argument, and stdin needs no quoting
    child.stdin?.on("error", () => {}); // EPIPE if the CLI died early -- the close handler reports why
    child.stdin?.end(input);
  });
}

// a missing binary is the single most likely setup failure, so name the fix instead of leaking
// a bare ENOENT to the UI
function spawnFailure(err: unknown): ClaudeCliError {
  const code = (err as { code?: string })?.code;
  if (code === "ENOENT") {
    return new ClaudeCliError(
      `Claude Code CLI not found (looked for "${CLI_BINARY}" on PATH). Install it from ` +
        `https://claude.com/claude-code, or set CLAUDE_PROVIDER=api in .env.local to use the Anthropic API instead.`
    );
  }
  const message = err instanceof Error ? err.message : String(err);
  return new ClaudeCliError(`Could not start the Claude Code CLI: ${message}`);
}

// pure so every failure branch is unit-testable without spawning anything
export function describeExitFailure(
  code: number | null,
  stderr: string,
  stdout: string
): string {
  const detail = (stderr.trim() || stdout.trim()).slice(0, ERROR_DETAIL_MAX_CHARS);
  const base = `Claude Code CLI exited with code ${code ?? "null"}`;
  if (looksLikeAuthFailure(detail)) {
    return (
      `${base}: not logged in. Run \`claude\` in a terminal and sign in with your Claude ` +
      `subscription, or set CLAUDE_PROVIDER=api in .env.local to use the Anthropic API instead.` +
      detailSuffix(detail)
    );
  }
  return base + detailSuffix(detail);
}

function looksLikeAuthFailure(detail: string): boolean {
  return /log ?in|logged out|sign in|authenticat|unauthorized|credential|invalid api key|oauth/i.test(
    detail
  );
}

function detailSuffix(detail: string): string {
  const trimmed = detail.trim().slice(0, ERROR_DETAIL_MAX_CHARS);
  return trimmed ? `: ${trimmed}` : "";
}

/**
 * Pulls the answer out of the CLI's JSON envelope: `structured_output` when present, else the
 * same object re-parsed from the `result` string. Reads only those two fields (plus the failure
 * flags) so a change in the envelope's shape fails loudly here instead of corrupting a resume.
 */
export function extractPayload(stdout: string): unknown {
  let envelope: CliEnvelope;
  try {
    envelope = JSON.parse(stdout.trim());
  } catch {
    throw new ClaudeCliError(
      `Claude Code CLI returned output that is not JSON${detailSuffix(stdout)}`
    );
  }

  if (envelope.is_error === true || (envelope.subtype && envelope.subtype !== "success")) {
    const detail = typeof envelope.result === "string" ? envelope.result : envelope.subtype ?? "";
    throw new ClaudeCliError(`Claude Code CLI reported an error${detailSuffix(detail)}`);
  }

  if (envelope.structured_output !== undefined && envelope.structured_output !== null) {
    return envelope.structured_output;
  }

  if (typeof envelope.result === "string") {
    try {
      return JSON.parse(envelope.result);
    } catch {
      throw new ClaudeCliError(
        `Claude Code CLI returned no structured output and its result was not JSON${detailSuffix(
          envelope.result
        )}`
      );
    }
  }

  throw new ClaudeCliError("Claude Code CLI response contained no structured output");
}
